export const Assets = {
  headerImage: require('../assests/images/header.png'),
  logo: require('../assests/images/logo.png'),
  backImage: require('../assests/images/backImage.png'),
  Union: require('../assests/images/Union.png'),
  homeCover: require('../assests/images/homeCover.png'),
  logo: require('../assests/images/logo.png'),
  intro1: require('../assests/images/intro1.png'),
  intro2: require('../assests/images/intro2.png'),
  intro3: require('../assests/images/intro3.png'),
  loginLogo: require('../assests/images/loginLogo.png'),
  splashLogo: require('../assests/images/splashLogo.png'),
  forwardArrow: require('../assests/images/forwardArrow.png'),
  docUpload: require('../assests/images/docUpload1.png'),
  docUploadActive: require('../assests/images/docUploadActive1.png'),
  homeLogo: require('../assests/images/homeLogo1.png'),

  user: require('../assests/images/user.png'),
  Password: require('../assests/images/Password.png'),

  twitter: require('../assests/images/twiter.png'),
  facebook: require('../assests/images/facebook.png'),
  google: require('../assests/images/google.png'),
  Email: require('../assests/images/Email.png'),
};
